In [2]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix

# Load Dataset Liga120192021.csv

In [8]:
df = pd.read_csv(r'F:\Kuliah\SEMESTER 7\Machine Learning\UAS\Liga120192021.csv')

In [12]:
df

Tanding  Pass1  Pass2  Pass3  Pass4  Pass5  Pass6  Pass7  Pass8  Pass9  \
0          0     11     24      2     20     10     11     13     11     16   
1          1     10     11     13     11     20     12     13     20     77   
2          2     16      8     16     17     21     22      3     20     10   
3          3     22     16      8     16      2     17     23      8     82   
4          4     20     12     16      8     16     17     21     23     22   
..       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
98        98     53     77     10     66     10     55     66     55     11   
99        99     30     22     23     22     74     23     12     23     13   
100      100     25     27     74     93     27     11     93     74     27   
101      101     27      7     27      7     25     12     27     13     21   
102      102     13     11     23      2     23     12     11     13     21   

     Pass10  
0        71  
1        71  
2        13  
3         4  
4        13  
..      ...  
98       10  
99        7  
100      25  
101       7  
102      25  

[103 rows x 11 columns]

# Klasifikasi Data Pada Kolom Pass4 terhadap Pass5

In [16]:
models = {}
for col in df.columns[1:]:
    x = df['Pass4'].values.reshape(-1, 1)
    y = df['Pass5'].values
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.40, random_state=48)
    model = LogisticRegression(max_iter=5000).fit(x_train, y_train)
    models[col] = model
    print("Accuracy for", col, ":", model.score(x_test, y_test))

Accuracy for Pass1 : 0.023809523809523808
Accuracy for Pass2 : 0.023809523809523808
Accuracy for Pass3 : 0.023809523809523808
Accuracy for Pass4 : 0.023809523809523808
Accuracy for Pass5 : 0.023809523809523808
Accuracy for Pass6 : 0.023809523809523808
Accuracy for Pass7 : 0.023809523809523808
Accuracy for Pass8 : 0.023809523809523808
Accuracy for Pass9 : 0.023809523809523808
Accuracy for Pass10 : 0.023809523809523808


# Klasifikasi Data Pada Kolom Pass8 terhadap Pass9

In [18]:
models = {}
for col in df.columns[1:]:
    x = df['Pass8'].values.reshape(-1, 1)
    y = df['Pass9'].values
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.40, random_state=48)
    model = LogisticRegression(max_iter=5000).fit(x_train, y_train)
    models[col] = model
    print("Accuracy for", col, ":", model.score(x_test, y_test))

Accuracy for Pass1 : 0.023809523809523808
Accuracy for Pass2 : 0.023809523809523808
Accuracy for Pass3 : 0.023809523809523808
Accuracy for Pass4 : 0.023809523809523808
Accuracy for Pass5 : 0.023809523809523808
Accuracy for Pass6 : 0.023809523809523808
Accuracy for Pass7 : 0.023809523809523808
Accuracy for Pass8 : 0.023809523809523808
Accuracy for Pass9 : 0.023809523809523808
Accuracy for Pass10 : 0.023809523809523808


# Confusion Matrix Pada Pass4

In [19]:
x = df.iloc[:, 1:].values
y = df['Pass4'].values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=40, random_state=48)
model = LogisticRegression(max_iter=10000).fit(x_train, y_train)
y_pred = model.predict(x_test)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 2 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 

# Confusion Matrix Pada Pass8

In [20]:
x = df.iloc[:, 1:].values
y = df['Pass8'].values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=40, random_state=48)
model = LogisticRegression(max_iter=10000).fit(x_train, y_train)
y_pred = model.predict(x_test)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 2 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0

# Clustering 2 Model Kolom

In [21]:
x = df.iloc[:, 1:].values
kmeans = KMeans(n_clusters=2, random_state=0).fit(x)
print("\nCluster Center:")
print(kmeans.cluster_centers_)


Cluster Center:
[[21.62820513 23.97435897 23.23076923 22.71794872 24.15384615 14.94871795
  25.33333333 19.62820513 34.12820513 27.35897436]
 [28.72       24.08       22.16       38.16       19.92       80.44
  35.16       43.68       16.2        25.56      ]]


C:\Users\Naji\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [23]:
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
x = df.iloc[:, :-1].values
k = 2
agg_clustering = agglomerativeClustering(n_cluster=k)
y_pred = agg_clustering.fit_predict(x)
colors = ['blue', 'green']
for i in range(k):
plt.scatter(x[y_pred == i, 0], x[y_pred ==i, 1], s=30, c=colors[i], label='cluster' + str(i+1))
plt.legend()
plt.show

IndentationError: expected an indented block after 'for' statement on line 8 (2166405867.py, line 9)